---
addons:
  apt:
    packages:
      - shellcheck

script:
  - shellcheck moleculew
  - shellcheck next-version.sh

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/
